2024-12-17 07:42:58,370 INFO    MainThread:30190 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2024-12-17 07:42:58,371 INFO    MainThread:30190 [wandb_setup.py:_flush():68] Configure stats pid to 30190
2024-12-17 07:42:58,371 INFO    MainThread:30190 [wandb_setup.py:_flush():68] Loading settings from /home/vidit_a_mfs.iitr/.config/wandb/settings
2024-12-17 07:42:58,371 INFO    MainThread:30190 [wandb_setup.py:_flush():68] Loading settings from /scratch/vidit_a_mfs.iitr/reverse-mark/tree-ring-watermark/wandb/settings
2024-12-17 07:42:58,371 INFO    MainThread:30190 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-17 07:42:58,372 INFO    MainThread:30190 [wandb_init.py:_log_setup():528] Logging user logs to /scratch/vidit_a_mfs.iitr/reverse-mark/tree-ring-watermark/wandb/run-20241217_074258-s1nrc43x/logs/debug.log
2024-12-17 07:42:58,372 INFO    MainThread:30190 [wandb_init.py:_log_setup():529] Logging internal logs to /scratch/vidit_a_mfs.iitr/reverse-mark/tree-ring-watermark/wandb/run-20241217_074258-s1nrc43x/logs/debug-internal.log
2024-12-17 07:42:58,372 INFO    MainThread:30190 [wandb_init.py:init():644] calling init triggers
2024-12-17 07:42:58,372 INFO    MainThread:30190 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {}
2024-12-17 07:42:58,372 INFO    MainThread:30190 [wandb_init.py:init():680] starting backend
2024-12-17 07:42:58,372 INFO    MainThread:30190 [wandb_init.py:init():684] sending inform_init request
2024-12-17 07:42:58,383 INFO    MainThread:30190 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-17 07:42:58,392 INFO    MainThread:30190 [wandb_init.py:init():697] backend started and connected
2024-12-17 07:42:58,395 INFO    MainThread:30190 [wandb_init.py:init():790] updated telemetry
2024-12-17 07:42:58,407 WARNING MsgRouterThr:30190 [router.py:message_loop():75] message_loop has been closed
2024-12-17 07:42:58,426 INFO    MainThread:30190 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2024-12-17 07:43:03,429 ERROR   MainThread:30190 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/home/vidit_a_mfs.iitr/anaconda3/envs/mark/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/vidit_a_mfs.iitr/anaconda3/envs/mark/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 825, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vidit_a_mfs.iitr/anaconda3/envs/mark/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
